fix(viewbodycard): Correct fatal error in Doc::viewbodycard() (refs #5327)
A fatal error could be triggered in Doc::viewbodycard() due to an
uninitialized variable ($currentFrameId):

> Fatal error: Call to a member function getOption() on a non-object in
> /.../FDL/Class.Doc.php on line 6946

The variable is now automatically initialized after the first attribute.