fix(viewbodycard): Correct a remaining fatal error in Doc::viewbodycard() (refs #5327)
Correct a remaining fatal error that could be triggered in
Doc::viewbodycard() due to an uninitialized variable ($currentFrameId):

> Fatal error: Call to a member function getOption() on a non-object in
> /.../FDL/Class.Doc.php on line 6974